### PR TITLE
Edits and comments

### PR DESCRIPTION
**Pull request by adrn**
Overall: it's done and looking great - we're submitting this week! 
* [x] Send around to co-authors and ask for final read-throughs. 
* [x] Draft a cover letter and send to the Davids + me.

Happy to explain any of the changes in person tomorrow if you have questions. It might be easier to look at the diffs by commit -- my editor auto-cleans trailing whitespace (sorry) so the first commit is just that. Other comments below:

* [x] Title, as is, should be "Kronos & Krios: Evidence for accretion of rocky
  planets in a pair of comoving G dwarfs" But reading the info from Nature, they
  say "...be general enough for readers outside the field to appreciate what the
  paper is about" - "G dwarfs" sounds jargon-y to me. Maybe go back to something
  like "solar-type stars" or ...?
* [x] End of first paragraph: "(section Table 1)"?
* [x] Why do you use bibcodes for cite keys? Makes it hard to quickly see (from
  the tex) what paper is being referenced
* [x] In paragraph on metallicity/abundance differences, "$\approx 60\%$" in
  what? Say explicitly "$\approx 60\%$ by number" or whatever.
* [x] Missing citation for planet-planet scattering (I had to add TODO to get
  latex to build the PDF)
* [x] Most places you say 15 Mearth, but some places you say 20 Mearth - go
  through and verify numbers!
* [x] For talks, would be cool to have a figure showing abundances of both stars
  after subtracting 15 Mearth from \bizarreone and 4 Mearth from \sunanalog
* [x] I'd actually be more inclined to remove the bit about proximity in
  phase-space and leave the orbits -- I think it's neat that the vertical
  actions seem to be larger than the Sun's. I'll come up with a reference about vertical action.
* [x] For chemical inhomogeneity, are there any theoretical studies that suggest
  a scale-length for chemical mixing? I feel like we need to comment on this,
  too -- maybe Eve has an idea? I'm happy to follow up with her on this if it would be useful.
* [x] I think Figure 5.3 is confusing with all of those lines. I would stick to
  one f_cz and do solid lines of different increasing thickness as the amount of
  added material increased.

### CODE REVIEW

**Comment by adrn** [comment]
And one other comment: Figures that show spectral ratios should have 1.0 as a tick mark (might mean you need to adjust ranges or ticks for symmetry / aesthetics).

**Comment by smoh** [comment]
Many many thanks!! I'll get to this asap.

> Why do you use bibcodes for cite keys? Makes it hard to quickly see (from
the tex) what paper is being referenced

I use autocompletion on any part of entries in bib file and didn't bother, but I can change that :)

**Comment by adrn** [comment]
@smoh oh, that makes sense, and I probably should be using that too...don't waste your time on changing the bibcodes!

**Comment by smoh** [comment]
Phew, I went with sun-like for title, and created issues of some items still left.

**Pull request merged**
